=== c4mjs/c4mjs/packages/workspace/src/workspace.schema.json
{
  "$ref": "#/definitions/WorkspaceDto",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "EntityDto": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        },
        "external": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "tech": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/EntityType"
        }
      },
      "required": ["address", "id", "name", "type"],
      "type": "object"
    },
    "EntityType": {
      "enum": ["container", "person", "system"],
      "type": "string"
    },
    "GroupDto": {
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string"
        },
        "desc": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "tags": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": ["address", "id", "name"],
      "type": "object"
    },
    "RelationshipDto": {
      "additionalProperties": false,
      "description": "Defines a Relationship Between a Sender and a Receiver",
      "properties": {
        "desc": {
          "description": "Description of the Message",
          "title": "Receiver",
          "type": "string"
        },
        "receiver": {
          "description": "ID of the Message Receiver",
          "title": "Receiver",
          "type": "string"
        },
        "sender": {
          "description": "ID of the Message Sender",
          "title": "Sender",
          "type": "string"
        },
        "tech": {
          "description": "Technology Used",
          "examples": ["HTTP"],
          "title": "tech",
          "type": "string"
        }
      },
      "required": ["receiver", "sender"],
      "title": "Relationship",
      "type": "object"
    },
    "WorkspaceDto": {
      "additionalProperties": false,
      "properties": {
        "entities": {
          "items": {
            "$ref": "#/definitions/EntityDto"
          },
          "type": "array"
        },
        "groups": {
          "items": {
            "$ref": "#/definitions/GroupDto"
          },
          "type": "array"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "relationships": {
          "items": {
            "$ref": "#/definitions/RelationshipDto"
          },
          "type": "array"
        },
        "styles": {
          "type": "string"
        },
        "version": {
          "description": "Version for the item",
          "examples": ["1.0.0"],
          "format": "semver",
          "title": "version",
          "type": "string"
        }
      },
      "required": ["entities", "groups", "id", "name", "relationships", "version"],
      "type": "object"
    }
  }
}

=== c4mjs/c4mjs/examples/big-bank-plc/workspace.json
{
  "id": "bigBankPlc",
  "name": "Big Bank PLC",
  "version": "1.0.0",
  "groups": [
    {
      "id": "internetBanking",
      "name": "Internet Banking System",
      "address": "internetBanking",
      "tags": []
    }
  ],
  "entities": [
    {
      "id": "customer",
      "address": "internetBanking.customer",
      "name": "Personal Banking Customer",
      "desc": "A customer of the bank, with personal bank accounts.",
      "external": false,
      "type": "person",
      "tags": []
    },
    {
      "id": "internetBankingSystem",
      "address": "internetBanking.internetBankingSystem",
      "name": "Internet Banking System",
      "desc": "Allows customers to view information about their bank accounts and make payments.",
      "external": false,
      "type": "system",
      "tags": []
    },
    {
      "id": "mainframeBankingSystem",
      "address": "internetBanking.mainframeBankingSystem",
      "name": "Mainframe Banking System",
      "desc": "Stores all of the core banking information about customers, accounts, transactions etc",
      "external": false,
      "type": "system",
      "tags": []
    },
    {
      "id": "emailSystem",
      "address": "internetBanking.emailSystem",
      "name": "Email System",
      "desc": "The internal Microsoft Exchange e-mail system.",
      "external": false,
      "type": "system",
      "tags": []
    },
    {
      "id": "webApp",
      "address": "internetBanking.internetBankingSystem.webApp",
      "name": "Web Application",
      "desc": "Delivers the static content and the Internet Banking single page application.",
      "external": false,
      "type": "container",
      "tags": []
    },
    {
      "id": "mobileApp",
      "address": "internetBanking.internetBankingSystem.mobileApp",
      "name": "Mobile Application",
      "desc": "Provides a limited subset of the internet banking functionality to customers via their mobile device.",
      "external": false,
      "type": "container",
      "tags": []
    },
    {
      "id": "database",
      "address": "internetBanking.internetBankingSystem.database",
      "name": "Database",
      "desc": "Stores user registration information, hashed authentication credentials, access logs etc.",
      "external": false,
      "type": "container",
      "tags": []
    },
    {
      "id": "singlePageApp",
      "address": "internetBanking.internetBankingSystem.singlePageApp",
      "name": "Single-Page Application",
      "desc": "Provides all of the Internet Banking functionality to the customers via their web browser",
      "external": false,
      "type": "container",
      "tags": []
    },
    {
      "id": "apiApp",
      "address": "internetBanking.internetBankingSystem.apiApp",
      "name": "Api Application",
      "desc": "Provides internet banking functionality via a JSON/HTTPS api.",
      "external": false,
      "type": "container",
      "tags": []
    }
  ],
  "relationships": [
    {
      "sender": "internetBanking.emailSystem",
      "receiver": "internetBanking.customer",
      "desc": "Sends email to"
    },
    {
      "sender": "internetBanking.customer",
      "receiver": "internetBanking.internetBankingSystem",
      "desc": "Views account balances, and makes payments using"
    },
    {
      "sender": "internetBanking.customer",
      "receiver": "internetBanking.internetBankingSystem.webApp",
      "desc": "Visits bigbank.com/ib using",
      "tech": "HTTPS"
    },
    {
      "sender": "internetBanking.internetBankingSystem",
      "receiver": "internetBanking.mainframeBankingSystem",
      "desc": "Stores all of the core banking information about customers, accounts, transactions etc"
    },
    {
      "sender": "internetBanking.internetBankingSystem.singlePageApp",
      "receiver": "internetBanking.internetBankingSystem.apiApp",
      "desc": "Delivers to the customers web browser"
    },
    {
      "sender": "internetBanking.mainframeBankingSystem",
      "receiver": "internetBanking.mainframeBankingSystem",
      "desc": "Stores all of the core banking information about customers, accounts, transactions etc"
    },
    {
      "sender": "internetBanking.customer",
      "receiver": "internetBanking.internetBankingSystem.apiApp",
      "desc": "Views account balances, and makes payments using"
    },
    {
      "sender": "internetBanking.internetBankingSystem.mobileApp",
      "receiver": "internetBanking.internetBankingSystem.apiApp",
      "desc": "Delivers to the customers web browser"
    },
    {
      "sender": "internetBanking.customer",
      "receiver": "internetBanking.internetBankingSystem.mobileApp",
      "desc": "Views account balances, and makes payments using"
    },
    {
      "sender": "internetBanking.customer",
      "receiver": "internetBanking.internetBankingSystem.singlePageApp",
      "desc": "Views account balances, and makes payments using"
    },
    {
      "sender": "internetBanking.internetBankingSystem.webApp",
      "receiver": "internetBanking.internetBankingSystem.singlePageApp",
      "desc": "Delivers to the customers web browser"
    },
    {
      "sender": "internetBanking.internetBankingSystem.apiApp",
      "receiver": "internetBanking.internetBankingSystem.apiApp",
      "desc": "Delivers to the customers web browser"
    }
  ]
}

=== c4mjs/c4mjs/packages/graphviz/src/__stubs__/workspace.json
{
  "id": "bigBankPlc",
  "name": "Big Bank PLC",
  "version": "1.0.0",
  "groups": [
    {
      "id": "internetBanking",
      "name": "Internet Banking System",
      "address": "internetBanking",
      "tags": []
    },
    {
      "id": "internetBankingAgent",
      "name": "Internet Banking Agent System",
      "address": "internetBankingAgent",
      "tags": []
    }
  ],
  "entities": [
    {
      "id": "customer",
      "address": "internetBanking.customer",
      "name": "Personal Banking Customer",
      "desc": "A customer of the bank, with personal bank accounts.",
      "external": false,
      "type": "person",
      "tags": []
    },
    {
      "id": "agent",
      "address": "internetBankingAgent.agent",
      "name": "Personal Banking Agent",
      "desc": "An agent of the bank, managing accounts on behalf of customers.",
      "external": false,
      "type": "person",
      "tags": []
    },
    {
      "id": "internetBankingSystem",
      "address": "internetBanking.internetBankingSystem",
      "name": "Internet Banking System",
      "desc": "Allows customers to view information about their bank accounts and make payments.",
      "external": false,
      "type": "system",
      "tags": ["critical"]
    },
    {
      "id": "mainframeBankingSystem",
      "address": "internetBanking.mainframeBankingSystem",
      "name": "Mainframe Banking System",
      "desc": "Stores all of the core banking information about customers, accounts, transactions etc",
      "external": true,
      "type": "system",
      "tags": []
    },
    {
      "id": "emailSystem",
      "address": "internetBanking.emailSystem",
      "name": "Email System",
      "desc": "The internal Microsoft Exchange e-mail system.",
      "external": true,
      "type": "system",
      "tags": []
    },
    {
      "id": "internetBankingManagementSystem",
      "address": "internetBankingAgent.internetBankingManagementSystem",
      "name": "Internet Banking Management System",
      "desc": "Allows agents to manage customer banking information and perform actions on their behalf",
      "external": false,
      "type": "system",
      "tags": []
    },
    {
      "id": "webApp",
      "address": "internetBanking.internetBankingSystem.webApp",
      "name": "Web Application",
      "desc": "Delivers the static content and the Internet Banking single page application.",
      "external": false,
      "type": "container",
      "tags": []
    },
    {
      "id": "singlePageApp",
      "address": "internetBanking.internetBankingSystem.singlePageApp",
      "name": "Single-Page Application",
      "desc": "Provides all of the Internet Banking functionality to the customers via their web browser",
      "external": false,
      "type": "container",
      "tags": []
    },
    {
      "id": "apiApp",
      "address": "internetBanking.internetBankingSystem.apiApp",
      "name": "Api Application",
      "desc": "Provides internet banking functionality via a JSON/HTTPS api.",
      "external": false,
      "type": "container",
      "tags": []
    },
    {
      "id": "mobileApp",
      "address": "internetBanking.internetBankingSystem.mobileApp",
      "name": "Mobile Application",
      "desc": "Provides a limited subset of the internet banking functionality to customers via their mobile device.",
      "external": false,
      "type": "container",
      "tags": []
    },
    {
      "id": "database",
      "address": "internetBanking.internetBankingSystem.database",
      "name": "Database",
      "desc": "Stores user registration information, hashed authentication credentials, access logs etc.",
      "external": false,
      "type": "container",
      "tags": ["database"]
    },
    {
      "id": "agentPortal",
      "address": "internetBankingAgent.internetBankingManagementSystem.agentPortal",
      "name": "Agent Portal",
      "desc": "Allows agents to log in and perform actions",
      "external": false,
      "type": "container",
      "tags": []
    }
  ],
  "relationships": [
    {
      "sender": "internetBankingAgent.internetBankingManagementSystem.agentPortal",
      "receiver": "internetBanking.internetBankingSystem.apiApp",
      "desc": "Sends API requests to"
    },
    {
      "sender": "internetBankingAgent.internetBankingManagementSystem",
      "receiver": "internetBanking.internetBankingSystem",
      "desc": "Sends API requests to"
    },
    {
      "sender": "internetBankingAgent.internetBankingManagementSystem",
      "receiver": "internetBanking.mainframeBankingSystem",
      "desc": "Gets account information from, and makes payments using"
    },
    {
      "sender": "internetBankingAgent.internetBankingManagementSystem",
      "receiver": "internetBanking.emailSystem",
      "desc": "Sends emails using"
    },
    {
      "sender": "internetBanking.customer",
      "receiver": "internetBanking.internetBankingSystem",
      "desc": "Views account balances, and makes payments using"
    },
    {
      "sender": "internetBankingAgent.agent",
      "receiver": "internetBankingAgent.internetBankingManagementSystem",
      "desc": "Views account balances, and makes payments using"
    },
    {
      "sender": "internetBanking.emailSystem",
      "receiver": "internetBanking.customer",
      "desc": "Sends email to"
    },
    {
      "sender": "internetBanking.customer",
      "receiver": "internetBanking.internetBankingSystem.webApp",
      "desc": "Visits bigbank.com/ib using",
      "tech": "HTTPS"
    },
    {
      "sender": "internetBanking.internetBankingSystem.webApp",
      "receiver": "internetBanking.internetBankingSystem.singlePageApp",
      "desc": "Delivers to the customers web browser"
    },
    {
      "sender": "internetBanking.customer",
      "receiver": "internetBanking.internetBankingSystem.mobileApp",
      "desc": "Views account balances, and makes payments using"
    },
    {
      "sender": "internetBanking.internetBankingSystem.mobileApp",
      "receiver": "internetBanking.internetBankingSystem.apiApp",
      "desc": "Makes API calls to"
    },
    {
      "sender": "internetBanking.internetBankingSystem",
      "receiver": "internetBanking.mainframeBankingSystem",
      "desc": "Gets account information from, and makes payments using"
    },
    {
      "sender": "internetBanking.internetBankingSystem.singlePageApp",
      "receiver": "internetBanking.internetBankingSystem.apiApp",
      "desc": "Makes API calls to"
    },
    {
      "sender": "internetBanking.internetBankingSystem.apiApp",
      "receiver": "internetBanking.internetBankingSystem.database",
      "desc": "Reads and writes to"
    },
    {
      "sender": "internetBanking.internetBankingSystem",
      "receiver": "internetBanking.emailSystem",
      "desc": "Sends emails using"
    },
    {
      "sender": "internetBankingAgent.agent",
      "receiver": "internetBankingAgent.internetBankingManagementSystem.agentPortal",
      "desc": "Perform actions using"
    },
    {
      "sender": "internetBanking.internetBankingSystem.apiApp",
      "receiver": "internetBanking.emailSystem",
      "desc": "Sends e-mail using"
    },
    {
      "sender": "internetBanking.customer",
      "receiver": "internetBanking.internetBankingSystem.singlePageApp",
      "desc": "Views account balances, and makes payments using"
    },
    {
      "sender": "internetBanking.internetBankingSystem.apiApp",
      "receiver": "internetBanking.mainframeBankingSystem",
      "desc": "Makes API calls to the silly system"
    }
  ]
}
